cask_args appdir: '/Applications'

brew 'ack'
brew 'coreutils'
brew 'tree'
brew 'gh'
brew 'awscli'
brew 'nodejs'
brew 'pyenv'

cask_args appdir: '/Applications'
cask 'the-unarchiver'
cask 'telegram'
cask 'docker-desktop'
cask 'visual-studio-code'
cask 'chatgpt'
cask 'notion'
cask 'whatsapp'
cask 'warp'
cask 'cursor'
cask 'temurin'
cask 'ollama-app'
cask 'chatgpt-atlas'
cask 'codex'
